/*
 * Automatically generated by 'ng g ng-alain:plugin icon'
 * @see https://ng-alain.com/cli/plugin#icon
 */

import {
  ArrowDownOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  LogoutOutline,
  SettingOutline,
  ToolOutline,
  UserOutline,
  LockOutline,
  CopyrightOutline,
  EnvironmentFill,
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  ArrowDownOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  LogoutOutline,
  SettingOutline,
  ToolOutline,
  UserOutline,
  LockOutline,
  CopyrightOutline,
  EnvironmentFill
];
